name: 🐛 Bug Report
description: Report a bug or unexpected behavior in PGO.
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT — Do NOT include PII
        **Never paste real personal data** (names, emails, addresses, phone numbers, URLs with personal info) in this issue. Use redacted placeholders like `[REDACTED]` or `user@example.com`.

        If this is a **security vulnerability**, do NOT open an issue. Follow [SECURITY.md](../SECURITY.md) instead.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: "What happened? What did you expect?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Run `pgo status`
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      description: Paste relevant logs. **Redact any PII before pasting.**
      render: shell
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - WSL
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12.x"
    validations:
      required: true

  - type: input
    id: pgo-version
    attributes:
      label: PGO version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: checkboxes
    id: pii-check
    attributes:
      label: PII confirmation
      description: Please confirm you have not included personal data.
      options:
        - label: I confirm this issue does NOT contain real personal information (PII).
          required: true
